### ISSUE TITLE
BadRequestException on process.getStatus()

### ISSUE THREAD

**Issue by sarbogast** [aioobe/cloudconvert#5]
I copy/pasted your sample code to try to convert a DOCX file into a PDF file, and when I call `process.getStatus()` inside `waitLoop`, I get a bad request exception. While trying to figure out what was wrong, I noticed that your CloudConvertService calls api on `api.cloudconvert.org` instead of `api.cloudconvert.com` as documented on CloudConvert's website. Could that be the problem?

**Comment by aioobe** [comment]
Does it work correctly if you use `.com` instead of `.org`?

**Comment by aioobe** [comment]
I've updated from `.org` to `.com` (https://github.com/aioobe/cloudconvert/commit/e0e0aef66adc6cc0fd4a3863afacdae444c5dd0e) and made a [1.1 release](http://central.maven.org/maven2/org/aioobe/cloudconvert/client/1.1/).

I tried the sample code from the readme and it seems to work. Please let me know if you're still experience issues.
